name: Unazed Spectaculum
description: software developer
avatar: https://avatars2.githubusercontent.com/u/29807271?s=460&v=4

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: barryclark/jekyll-now
  instagram:
  linkedin:
  pinterest:
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus:


disqus:
google_analytics:

url: https://unazed.github.io

baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded 

gems:
  - jekyll-sitemap 
  - jekyll-feed 

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
