name: Unazed Spectaculum
description: software developer
avatar: https://avatars2.githubusercontent.com/u/29807271?s=460&v=4


disqus:
google_analytics:

url: https://unazed.github.io

baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: Pygments
  syntax_highlighter_opts:
    css_class: 'highlight'

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  posts:
    output: true

sass:
  style: :expanded 

gems:
  - jekyll-sitemap 
  - jekyll-feed 

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-dinky
